/**
 * Copyright 2013 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Eclipse Public License version 1.0, available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.jboss.forge.scaffold.angularjs;

import java.io.FileNotFoundException;

import javax.ws.rs.Path;

import org.jboss.forge.parser.java.JavaClass;
import org.jboss.forge.parser.java.JavaSource;
import org.jboss.forge.resources.java.JavaResource;
import org.jboss.forge.resources.java.JavaResourceVisitor;

/**
 * A {@link JavaResourceVisitor} that inspects {@link JavaResource}s and verifies whether they are JAX-RS Resources that employ
 * the same conventions as the ones generated by the Forge REST plugin. 
 */
class ResourcePathVisitor implements JavaResourceVisitor {

    private String entityName;
    private String path = null;
    private boolean found = false;

    public ResourcePathVisitor(String entityName) {
        this.entityName = entityName;
    }

    @Override
    public void visit(JavaResource javaResource) {
        if (!found) {
            try {
                JavaSource<?> javaSource = javaResource.getJavaSource();
                if (javaSource instanceof JavaClass) {
                    JavaClass javaClass = (JavaClass) javaSource;
                    if (javaClass.getName().equals(entityName + "Endpoint") && javaClass.hasAnnotation(Path.class)) {
                        this.path = javaClass.getAnnotation(Path.class).getStringValue();
                        found = true;
                    }
                }
            } catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            }
        }
    }

    public String getPath() {
        return path;
    }

}